[build]
command = """
python3 -m pip install --upgrade pip &&
pip install -r requirements.txt &&
npm install --legacy-peer-deps &&
npm run build
"""
publish = "dist"

[build.environment]
NODE_VERSION = "20"
PYTHON_VERSION = "3.10"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
